#!/bin/bash

TSESSION="arkattbrain_new"
TSERVER="arkatt_u_gruchy"

# Check if the session exists, if so attach it, else make Barsawia
if [ $(tmux -L ${TSERVER} ls 2>/dev/null | grep -c "^${TSESSION}:") != 0 ]; then
        echo "Session ${TSESSION} already exists. Attaching."
        tmux -L ${TSERVER} att -t ${TSESSION}
        exit 0;
else
        echo "Session ${TSESSION} does not exist. Creating."
        tmux -L ${TSERVER} new -d -s ${TSESSION} "tt++ portserver.tin"
        tmux -L ${TSERVER} att -t ${TSESSION}
fi
